[db]
url = "libsql://media-naval.turso.io"
auth_token = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3MjE4MDE0NzAsImlkIjoiMTM3YjY2YmItZDEwZS00ZTU5LTkxNzUtNzQyMGVkMTQzMDc2In0.OIcPp8wYW6nbPQ5nIJjEX-jw7EesAm2sK3UfUUg396Z4XVc3MYLXtgNoc_hWuePjAghevfE-BWV0nO1LWhZJCQ"

xata_user = "bpmg26"
xata_api_key = "xau_VzvO6GQkucnGGrQoGyk4TIiF50V8WuCG1"

[trakt]
